---
name: Vendor Dependencies Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  depscheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'
      - run: chmod -R +x ./scripts
      - run: bash scripts/gogetcookie.sh
      - run: make depscheck
